environments: 
  default:
    values:
      - values.yaml

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: runix
    url: https://helm.runix.net
    
releases:
  - name: postgres
    chart: bitnami/postgresql
    values:
      - auth:
          postgresPassword: {{ .Values.postgres.password }}
      - primary:
          service:
            type: LoadBalancer
  - name: pgadmin
    chart: runix/pgadmin4
    values:
      - env:
          email: {{ .Values.pgadmin.email }}
          password: {{ .Values.postgres.password }}
      - service:
          port: 5433
          type: LoadBalancer