environments: 
  default:
    values:
      - values.yaml

---

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
    
releases:
  - name: postgres
    chart: bitnami/postgresql
    values:
      - auth:
          postgresPassword: {{ .Values.postgres.password }}
      - primary:
          service:
            type: {{ .Values.postgres.service.type }}